# Github del curso

https://github.com/zamorays/cursoDatosGeograficos

# Data

https://www.dropbox.com/s/o7arhhlesislqch/data.zip?dl=0

### ¿Qué es Data Science? 

La Ciencia de Datos trata 
del 
estudio de la 
extracción generalizada de 
conocimiento a partir de información.



“Un Científico de Datos, es la persona que sabe más de estadística que cualquier programador y que a la vez sabe más programación que cualquier estadístico“

[Josh Wills](https://www.linkedin.com/in/josh-wills-13882b/)



Ingeniería de datos, método científico, matemáticas, estadística, computación avanzada, visualización y expertos en los distintos ámbitos de especialidad.


 [Un gran artículo sobre como ser un científico de datos.](http://www.solocodigoweb.com/blog/2017/01/30/quiero-ser-un-cientifico-de-datos-por-donde-empiezo/)

### La caja de herramientas
* Bases de datos relacionales: SQL, (postgis como extensión de postgresql)
* Bases de datos no relacionales,  NoSQL, Cassandra, MongoDb, ...etc
* Lenguajes de programación: R, Python (Pandas+Geopandas, Fiona, Shapely, geomatplotlib, rasterio)
* Machine Learning (Scikit-Learn, pybrain, !!!TENSORFLOW!!!)
* Programación de altas prestaciones, programación distribuida, Hadoop (Hadoop no! Cloudera), Spark (Qué no! PySpark) 

![title](img/data-science.jpg)

![title](img/ciclo-vida.png)

### Sitios de interés

* Common Crawl, que pone a disposición un gran número de datos de miles de  millones de webs:

http://www.sorayapaniagua.com/2013/01/28/common



* Kaggle, un sitio interesante en el que existen competiciones públicas extracción de conocimiento y predicción a partir de datos:

http://www.kaggle.com





# Numpy

## Documentación
https://docs.scipy.org/doc/numpy-1.13.0/index.html

In [1]:
import numpy as np

instalacion:
ubuntu: pip install numpy

windows: conda install numpy

In [2]:
print('arreglo dimension 3x1')
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a[0])


arreglo dimension 3x1
[1 2 3]
(3,)
1


In [3]:
print('arreglo dimension 2x3')
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0])
print(b[0][0])

arreglo dimension 2x3
[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3]
1


In [ ]:
print('arreglo dimension 3x1')
c = np.array([[1,2],[3,4],[5,6]])
print(c)
print(c.shape)

In [6]:
# matriz de ceros
a = np.zeros((2,2))   
a        

array([[0., 0.],
       [0., 0.]])

In [5]:
# matriz de unos
b = np.ones((1,2))    
b

array([[1., 1.]])

In [ ]:
# matriz de sietes
c = np.full((2,2), 7)  
print(c)                       

In [ ]:
#matriz diagonal
d = np.eye(2)         
print(d)    

In [ ]:
# matriz con numeros aleatorios
e = np.random.random((2,2))  
print(e)  

# Distribuciones

instalacion:
ubuntu: pip install matplotlip

windows: conda install matplotlib

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
x = np.random.random(size = 10)
sns.distplot(x)
plt.show()


In [ ]:
x = np.random.normal(loc=3,scale=2,size = 100)
sns.distplot(x)
plt.show()



In [ ]:
x = np.random.poisson(lam=1,size = 10000000)
sns.distplot(x)
plt.show()

In [ ]:
# numeros aleatorios
print(np.random.randint(low=1,high=100,size=5))

In [ ]:
print(np.random.choice([2.0,1,3.0,5.0],3))

# Operaciones matriciales

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

In [ ]:
# suma y resta
print(x+y)
print(x-y)

In [ ]:
# multiplicación y división
print(x*y)   #producto matricial elemento a elemento
print()
print(x/y)

In [ ]:
print(np.sin(x))
print()
print(np.cos(x))
print()
print(np.sqrt(x))
print()
print(np.dot(x,y))  #producto matricial
print()
print(x.dot(y))

# Broadcasting

In [ ]:

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y) 

# reshape

In [ ]:
u = np.random.randint(1,10,size=10
                    )
print(u)

In [ ]:
a = np.reshape(u, (2,5))
print(a)



In [ ]:
a = np.reshape(u,[5,2])
print(a)

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)
print(False is False)
print(np.arange(1,100000,2))

# Pandas

## Documentación

[http://pandas.pydata.org/pandas-docs/stable/]

instalacion:
ubuntu: pip install pandas


windows: conda install pandas

In [ ]:
import pandas as pd

## Series

In [ ]:
s=pd.Series([1,2,3,4,5])
print(s)

In [ ]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)


### Las series pueden trabajarse con arreglos(listas) o como diccionarios

In [ ]:
print(s[:3])
print(s['c'])

In [ ]:
s=pd.Series(np.random.random(5),index=s.index)
print(s)

In [ ]:
s=pd.Series(np.random.random(5),index=s.values)
print(s)

In [ ]:
np.exp(s)

**Quiz 1:** Crea una matriz de 2x5 que contenga los elementos de 1 a 10

In [ ]:
s=pd.Series(np.arange(0,10))

print(s)
print(s[:5])
print(s[5:])
print(s[:5]+s[5:])

In [ ]:
u=s[:5]
v=s[5:]
u=u.reset_index(drop=True)
v=v.reset_index(drop=True)
print(u+v)

## DataFrame


In [ ]:
diccionario={'uno':np.random.randint(0,5,10,),
            'dos':np.random.random(10)}

In [ ]:
df = pd.DataFrame(diccionario)
df

In [ ]:
df.columns=['floats','ints']
df.index=list('confirmado')
print(df)

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df=pd.DataFrame(np.array([[1,2,'hola'],[3,4,'mundo']]),columns=['col1','col2','col3'],index=['row1','row2'])

In [ ]:
df

In [ ]:
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df=pd.DataFrame(data)
df

## agregando y eliminando columnas

In [ ]:
df['d'] = df['a']/df['b'] # df.a/df.b
df

In [ ]:
del df['d'] 

In [ ]:
del df.a # # aqui no funciona del df.d, puesto que tomaria a d como atributo de df
df

## Lectura y escritura

## Formatos principales
* csv
* json
* html
* hdf5
* parquet
* stata
* sql
* google big query

In [ ]:
df=pd.DataFrame(data)
df

In [ ]:
df.to_json('json_split.json',orient='split')
df.to_json('json_index.json',orient='index')
df.to_json('json_records.json',orient='records')

In [ ]:
pd.read_json('json_records.json')

In [ ]:
df.to_csv('dataframe_csv.csv')
df.to_html('html.html')
df.to_hdf('hdf.hdf',key='x')

In [ ]:
df = pd.read_csv('CIE.csv',sep=',',index_col=0)
df

## Head and Tail

In [ ]:
df.head()

## shape, info, len...

In [ ]:
df.info()

# Todo a mayúsculas

In [ ]:
df.columns =[x.lower() for x in df.columns]  # el nombre de las columnas funciona como una lista
df.head()

# Análisis descriptivo


* count
* sum
* mean
* mad
* median
* min
* max
* mode
* abs
* prod
* std
* var
* sem
* skew
* kurt
* quantile
* cumsum
* cumprod
* cummax
* cummin

In [ ]:
# Describe
df.leu.describe(percentiles=[0.10,0.20,0.30,0.40])  
#es lo mismo que df['leu'].describe(percentiles=[0.10,0.20,0.30,0.40])

# Missing data

In [ ]:
# Eliminar NAs
df.dropna()

In [ ]:
df

In [ ]:
df.dropna(subset=['de2'],inplace=True)

In [ ]:
df = pd.read_csv('CIE.csv')
df.fillna(0)

# Selección de datos

In [ ]:
# seleccionando por posicion
df[2:4]

In [ ]:
# seleccionando columnas
df[['NUM','NC']].tail()

In [ ]:
## seleccionando por indice y columnas por posicion
df.iloc[2:4,3:6]

In [ ]:
df.loc[df.SEXO=='M',['Id1','hora1']].head()

In [ ]:
df.loc[(df.EDAD.astype(int)>30)&(df.SEXO=='H'),:]

# operaciones booleanas
* negación  ~
* and    &
* or     |

In [ ]:
## Ordenar
df.sort_values(['LEU']).head().loc[:,['Id1','LEU']]

In [ ]:
df.loc[df.SEXO.isin(['M','F']),:].sample(5).sort_values('EXPEDIENTE',ascending=True)

In [ ]:
df.loc[df.NC<40,'NC']=40
df

# Agrupando

In [ ]:
df=pd.read_csv('probe.probe').sample(100000)
df.head()

In [ ]:
df=df.rename(columns={'Unnamed: 0':'id'})
df.head()

In [ ]:
print(len(df))
df=df.drop_duplicates()
len(df)

In [ ]:
df.plot(x='x',y='y',kind='scatter')

In [ ]:
df.groupby('provider').mean()

In [ ]:
df.groupby('provider').mean().plot(x='x',y='y',kind='scatter')

In [ ]:
df['timestamp'] = pd.to_datetime(df['timestamp'],format= '%Y-%m-%dT%H:%M:%SZ')
df['timestamp']=df.timestamp.dt.tz_localize('UTC').dt.tz_convert('America/Mexico_City') 

In [ ]:
df['hora']=df.timestamp.dt.hour
df.head()

In [ ]:

df.loc[df.speed>0,:].groupby(['provider','hora'])['speed'].mean().reset_index().head(24)


In [ ]:
df.loc[df.speed>0,:].groupby(['provider','hora'])['speed'].mean().reset_index().head(24).plot(x='hora',y='speed')

In [ ]:
df.loc[df.speed>0].groupby('provider')['speed','x','y'].agg(['mean','count','median','std'])

In [ ]:
def sum_coordenadas(row):
    return row.x+row.y
def limite_outlier_superior(column):
    return column.mean()+2*column.std()
def limite_outlier_inferior(column):
    return column.mean()-2*column.std()

In [ ]:
df['suma_coordenadas'] = df.apply(sum_coordenadas,axis=1)
df.head()

In [ ]:
df[['id','x','y','speed','provider','hora']].apply(limite_outlier_superior)

In [ ]:
df[['id','x','y','speed','provider','hora']].groupby('provider')\
              .apply(limite_outlier_superior)

In [ ]:
limite_outliers = df[['id','x','y','speed','provider','hora']].groupby('provider')\
                    .agg([limite_outlier_inferior,limite_outlier_superior])
limite_outliers

## Diferencias entre map, apply y applymap

In [ ]:
def sumar_1(element):
    return element+1
def promedio_armonico(serie):
    
    return len(u)/sum(1/serie)

In [ ]:
df.head()

In [ ]:
df.x.map(sumar_1).head()


In [ ]:
df.loc[df.speed>0,['id','x','y','speed','provider']].apply(promedio_armonico)


In [ ]:
df.loc[df.speed>0,['id','x','y','speed','provider']].apply(promedio_armonico,axis=1).head()


In [ ]:
df.loc[:,['id','x','y','speed','provider']].applymap(sumar_1).head()

## Rolling

In [ ]:
df.loc[:,['id','x','y','speed','provider']].rolling(5,center=True).apply(np.mean).head(10)

In [ ]:
limite_outliers = limite_outliers['speed'].reset_index()
limite_outliers

## Joins

In [ ]:
u = pd.merge(df,limite_outliers,how='inner',on='provider')
u.head()

In [ ]:
u.loc[(u.speed<u.limite_outlier_inferior) | (u.speed>u.limite_outlier_superior),:].head()

## Append

In [ ]:
len(df)

In [ ]:
u = df.sample(50000)
v = df.loc[~u.index.isin(u),:]

In [ ]:
print(len(u),len(v))

In [ ]:
print(len(u.append(v)))  #ignore_index=False

In [ ]:
len(pd.concat([u,v]))

In [ ]:
u = u[['x','y']]
v = v[['x','y']]
pd.concat([u,v],axis=1).head(10)
   # por qué aparecen los na's?

In [ ]:
u.reset_index(drop=True,inplace=True)
v.reset_index(drop=True,inplace=True)
pd.concat([u,v],axis=1).head(10)

In [ ]:
df1 = pd.DataFrame({'col1': [0, 1], 'col_left':['a', 'b']})
df2 = pd.DataFrame({'col1': [1, 2, 2],'col_right':[2, 2, 2]})
pd.merge(df1, df2, on='col1', how='right', indicator=True)  #.dtypes

## Testeo de hipótesis

** Quiz **  Crea una función que toma dos series y testee si las medias de ambas series son iguales con un nivel de significancia del 5%

In [ ]:


df.groupby('provider').agg(['mean','size'])

In [ ]:
def prueba_medias(serie1,serie2):
    media1 = serie1.mean()
    media2 = serie2.mean()
    std1 = serie1.std()
    std2 = serie2.std()
    n1 = len(serie1)
    n2 = len(serie2)
    z_critica=1.96
    sigma2 = ((n1-1)*std1**2+(n2-1)*std2**2)/(n1+n2-2)
    varianza_combinada = np.sqrt(sigma2*(1.0/float(n1)+1.0/float(n2)))
    z_calculada = (media1-media2)/varianza_combinada
    if abs(z_calculada) < z_critica: return True
    return False
serie1 = df.loc[df.provider==6,'hora']
serie2 = df.loc[df.provider==7,'hora']
prueba_medias(serie1,serie2)

## Tablas pivote

In [ ]:
df['fecha']=df.timestamp.dt.date
df.head()

In [ ]:
u = df.loc[df.speed>0,:].groupby(['provider','fecha'])[['x','y','speed']].mean().reset_index()
u

In [ ]:
u.pivot(index='fecha', columns='provider', values='speed')

## Series de tiempo

In [ ]:
u = pd.DataFrame(np.random.randn(1000, 4), index=pd.date_range('1/1/2000', periods=1000), columns=list('ABCD'))
u = u.cumsum()
u.plot()

In [ ]:

u[['mA','mB','mC','mD']] = u.rolling(100).mean()
u.plot()

In [ ]:
pd.to_datetime(pd.Series(['Jul 31, 2009','2010-01-10', None ]))

In [ ]:
pd.to_datetime(['04-01-2012 10:00'], dayfirst=True)

In [ ]:
pd.to_datetime('2010/11/12')

In [ ]:
pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')

In [ ]:
from datetime import datetime
start = datetime(2011, 1, 1)
end = datetime(2012, 1, 1)
index = pd.date_range(start, end)
index

In [ ]:
pd.date_range(start, periods=1000, freq='M')

In [ ]:
Property	Description
year	The year of the datetime
month	The month of the datetime
day	The days of the datetime
hour	The hour of the datetime
minute	The minutes of the datetime
second	The seconds of the datetime
microsecond	The microseconds of the datetime
nanosecond	The nanoseconds of the datetime
date	Returns datetime.date (does not contain timezone information)
time	Returns datetime.time (does not contain timezone information)m
dayofyear	The ordinal day of year
weekofyear	The week ordinal of the year
week	The week ordinal of the year
dayofweek	The number of the day of the week with Monday=0, Sunday=6
weekday	The number of the day of the week with Monday=0, Sunday=6
weekday_name	The name of the day in a week (ex: Friday)
quarter	Quarter of the date: Jan-Mar = 1, Apr-Jun = 2, etc.
days_in_month	The number of days in the month of the datetime
is_month_start	Logical indicating if first day of month (defined by frequency)
is_month_end	Logical indicating if last day of month (defined by frequency)
is_quarter_start	Logical indicating if first day of quarter (defined by frequency)
is_quarter_end	Logical indicating if last day of quarter (defined by frequency)
is_year_start	Logical indicating if first day of year (defined by frequency)
is_year_end	Logical indicating if last day of year (defined by frequency)
is_leap_year	Logical indicating if the date belongs to a leap year

In [ ]:
#df.timestamp.dt.is_month_end

In [ ]:
#analicemos con detalle las siguientes líneas

df['timestamp'] = pd.to_datetime(df['timestamp'],format= '%Y-%m-%dT%H:%M:%SZ')
df['timestamp']=df.timestamp.dt.tz_localize('UTC').dt.tz_convert('America/Mexico_City') 

# Tarea 

* Crea un script que calcule los primeros N números de fibonacci
* Crea una función que calcule los coeficientes de binomiales C(n,k)
* Agrega un atributo a la clase coordCityP (si desea cámbiele el nombre) que consista en una lista que contiene las coordenadas del polígono que define a la ciudad
* Agregue un método que devuelva las coordenadas cartesianas en la clase coordCityP
* Agregue un método que devuelva las coordenadas de la proyección estereográfica tanto en coordenadas cartesianas como en cilíndricas https://en.wikipedia.org/wiki/Stereographic_projection

* Del archivo Coppel.csv calcule:

 * Número de tiendas por estado
 * Número de tiendas por municipio
 * Número de altas por mes y año 